/vis/scene/create
#/vis/open OGLSX
# You can also set the size and position of the window if you like
/vis/open OGLSX 1000x1000-0+0
/vis/ogl/set/printSize 1000 1000

# Vis Settings for SK
#/vis/viewer/zoom 1.2
#/vis/viewer/set/viewpointThetaPhi 45 45 deg
#/vis/viewer/set/viewpointThetaPhi 110 0 deg
#/vis/viewer/set/upVector 0 0 1

# Vis Settings for ANNIE
/vis/viewer/zoom 1.2
/vis/viewer/set/viewpointThetaPhi 80 10 deg
/vis/viewer/set/upVector 0 1 0
/vis/viewer/panTo -1 1

# Vis settings for HK
#/vis/viewer/set/upVector 0 1 0
#/vis/viewer/set/viewpointThetaPhi 50 165 deg
#/vis/viewer/zoom 1.6
#/vis/ogl/set/printMode pixmap
#/vis/ogl/printEPS

/vis/scene/add/hits
/vis/scene/add/trajectories
#/vis/scene/endOfEventAction accumulate

#/vis/scene/add/axes 0 0 0 5 m
/vis/scene/add/scale 2 m x 1 0 0 manual 1 0 0 m
/vis/scene/add/scale 2 m y 0 1 0 manual 0 1 0 m 
/vis/scene/add/scale 2 m z 0 0 1 manual 0 0 1 m
#/vis/viewer/set/defaultTextColour 1 1 1	should be default, can give argument "white", use ! to unchange values but set further parameters
/vis/scene/add/text 1 -0.2 0 m 16 0 0 x		# red
/vis/scene/add/text 0 0.8 -0.1 m 16 0 0 y	# green
/vis/scene/add/text 0 -0.2 1 m 16 0 0 z		# blue
#text [x] [y] [z] [unit] [font_size] [x_offset] [y_offset] [text]
#/vis/scene/add/hits
#/vis/scene/add/trajectories smooth
#/vis/filtering/trajectories/create/attributeFilter PDG
#/vis/filtering/trajectories/attributeFilter-0/add 100
#/vis/filtering/trajectories/attributeFilter-0/invert true
#/vis/filtering/trajectories/mode hard
#/vis/filtering/trajectories/create/originVolumeFilter
#/vis/filtering/trajectories/originVolumeFilter-0/add MRDscints
#/vis/filtering/trajectories/originVolumeFilter-0/add MRDsteels
#/vis/filtering/trajectories/originVolumeFilter-0/add MRDalus
#/vis/filtering/trajectories/originVolumeFilter-0/verbose false

