# set the list of root files containing primaries to import into the primary generator TChain
# be sure that the neutrinosDirectory is set before setting the primariesDirectory!
/mygen/neutrinosdirectory /home/marc/LinuxSystemFiles/WChSandBox/build/fluxesandtables/gntp.*.ghep.root
/mygen/primariesdirectory /home/marc/LinuxSystemFiles/WChSandBox/build/fluxesandtables/annie_tank_flux.*.root
/mygen/primariesoffset 0
